/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./../components/atoms/checkbox.vue')['default']
    Filedownload: typeof import('./../components/molecules/filedownload.vue')['default']
    Fileupload: typeof import('./../components/molecules/fileupload.vue')['default']
    FileuploadEnhanced: typeof import('./../components/molecules/fileuploadEnhanced.vue')['default']
    Header: typeof import('./../components/organisms/header.vue')['default']
    OutlineButton: typeof import('./../components/atoms/outlineButton.vue')['default']
    ProjectArchitecture: typeof import('./../components/molecules/projectArchitecture.vue')['default']
    Pulldown: typeof import('./../components/atoms/pulldown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolidButton: typeof import('./../components/atoms/solidButton.vue')['default']
    StepCard: typeof import('./../components/atoms/stepCard.vue')['default']
  }
}
