/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AddCategory: (typeof import("./../components/addCategory.vue"))["default"];
    AddCategoryButton: (typeof import("./../components/addCategoryButton.vue"))["default"];
    AddTask: (typeof import("./../components/addTask.vue"))["default"];
    CategoryTab: (typeof import("./../components/categoryTab.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    ShowTask: (typeof import("./../components/showTask.vue"))["default"];
  }
}
